#---------------------------------------------- eureka slave1 注册中心配置 ----------------------------------------------------
server:
  port: 18761

spring:
  application:
    name: fyqz-server-eureka # 应用名称
  profiles: slave1 # 【eureka服务器集群 —— 节点1】，用于main方法启动的时候，用户需要输入的内容。标识启动的是哪一个eureka服务器；
  #服务监控
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: fyqz
        password: 123456

  security:
    user:
      name: fyqz
      password: 123456

eureka:
  instance:
    hostname: slave1 # 服务所在主机（一般都是配置域名）；本地测试的话，需要在 host 文件中指定虚拟域名
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@slave1:18761/eureka # eureka服务器的地址
    fetch-registry: false # 获取注册列表
    register-with-eureka: false # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
 #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务

management:
  security:
    enabled: false # 关闭安全验证（或者设置用户名和密码）。客户端访问一些接口的时候，才不会出现：401 Unauthorized权限的错误 ——
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节

# 注意下面是三个横杠：在单一文件中，可用连续三个连字号（---）区分多个文件（节省多个yml文件的配置，在一个yml文件中就可配置）。
---

#---------------------------------------------- eureka slave2 注册中心配置 ----------------------------------------------------
server:
  port: 28761

spring:
  application:
    name: fyqz-server-eureka # 应用名称
  profiles: slave2 # 【eureka服务器集群 —— 节点2】 用于main方法启动的时候，用户需要输入的内容。标识启动的是哪一个eureka服务器；
  #服务监控
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: fyqz
        password: 123456
  security:
    user:
      name: fyqz
      password: 123456

eureka:
  instance:
    hostname: slave2 # 服务所在主机（一般都是配置域名；本地测试的话，需要在 host 文件中指定虚拟域名
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@slave1:28761/eureka # eureka服务器的地址
    fetch-registry: false # 获取注册列表
    register-with-eureka: false # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
 #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务

management:
  security:
    enabled: false # 关闭安全验证（或者设置用户名和密码）。客户端访问一些接口的时候，才不会出现：401 Unauthorized权限的错误 ——
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节
